# Generated by Django 5.0.1 on 2024-01-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
