# Generated by Django 5.0.1 on 2024-02-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0004_alter_producto_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod',
            field=models.CharField(max_length=20),
        ),
    ]
