# Generated by Django 5.0.1 on 2024-02-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0006_historialproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialproducto',
            name='cod_anterior',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
