# Generated by Django 5.0.1 on 2024-02-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0008_alter_producto_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialproducto',
            name='id_anterior',
            field=models.CharField(max_length=255),
        ),
    ]
