# Generated by Django 5.0.1 on 2024-02-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0009_alter_historialproducto_id_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialproducto',
            name='precio_actualizado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
