# Generated by Django 5.0.1 on 2024-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0012_facturaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('condicion_venta', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transf_bancaria', 'Transferencia Bancaria'), ('mercadopago', 'MercadoPago'), ('naranjax', 'NaranjaX'), ('uala', 'Ualá'), ('transferencia_otro', 'Transferencia Otro')], max_length=100)),
                ('condicion_fiscal', models.CharField(max_length=100)),
                ('cuit_dni', models.CharField(max_length=20)),
                ('fecha_vencimiento_pago', models.DateField()),
            ],
        ),
    ]
