# Generated by Django 5.0.1 on 2024-03-15 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0013_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='seleccionado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductoSeleccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlStock.producto')),
            ],
        ),
    ]
