# Generated by Django 5.0.1 on 2024-03-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0014_producto_seleccionado_productoseleccionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='seleccionado',
        ),
        migrations.DeleteModel(
            name='ProductoSeleccionado',
        ),
    ]
