# Generated by Django 5.0.1 on 2024-03-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0015_remove_producto_seleccionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='condicion_venta',
            field=models.CharField(max_length=100),
        ),
    ]
