# Generated by Django 5.0.1 on 2024-03-16 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0016_alter_cliente_condicion_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('condicion_venta', models.CharField(max_length=100)),
                ('cuit_dni', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlStock.producto')),
            ],
        ),
    ]
