# Generated by Django 5.0.1 on 2024-03-16 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0017_historialfactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialfactura',
            name='cuit_dni',
        ),
        migrations.AddField(
            model_name='historialfactura',
            name='condicion_fiscal',
            field=models.CharField(default='Arg.Consumidor Final', max_length=100),
        ),
        migrations.AddField(
            model_name='historialfactura',
            name='fecha_vencimiento_pago',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialfactura',
            name='condicion_venta',
            field=models.CharField(default='efectivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='historialfactura',
            name='domicilio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historialfactura',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
