# Generated by Django 5.0.1 on 2024-03-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0018_remove_historialfactura_cuit_dni_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialFactura',
        ),
    ]
