# Generated by Django 5.0.1 on 2024-03-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0020_historialfactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_vencimiento_pago',
        ),
        migrations.RemoveField(
            model_name='historialfactura',
            name='fecha_vencimiento_pago',
        ),
    ]
