# Generated by Django 5.0.1 on 2024-03-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0021_remove_cliente_fecha_vencimiento_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialfactura',
            name='producto',
        ),
        migrations.DeleteModel(
            name='FacturaProducto',
        ),
        migrations.DeleteModel(
            name='HistorialFactura',
        ),
    ]
