# Generated by Django 5.0.1 on 2024-03-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0024_alter_facturaproducto_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturaProducto',
        ),
    ]
