# Generated by Django 5.0.1 on 2024-03-17 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0025_delete_facturaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlStock.historialfactura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlStock.producto')),
            ],
        ),
    ]
