# Generated by Django 5.0.1 on 2024-03-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0026_facturaproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturaProducto',
        ),
    ]
