# Generated by Django 5.0.1 on 2024-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0028_facturaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialfactura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
