# Generated by Django 5.0.1 on 2024-03-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0029_historialfactura_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('condicion_venta', models.CharField(max_length=100)),
                ('condicion_fiscal', models.CharField(max_length=100)),
                ('cuit_dni', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlStock.producto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='controlStock.registrofactura')),
            ],
        ),
    ]
