# Generated by Django 5.0.1 on 2024-03-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0032_registrofactura_detallefactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto',
        ),
        migrations.DeleteModel(
            name='RegistroFactura',
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
    ]
