# Generated by Django 5.0.1 on 2024-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0033_remove_detallefactura_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_carrito',
            field=models.BooleanField(default=False),
        ),
    ]
