# Generated by Django 5.0.1 on 2024-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0035_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
