# Generated by Django 5.0.1 on 2024-03-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0036_producto_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproducto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
